[test]
preload = ["./test.dom.ts", "./test.setup.ts"]
coverage = true
coverageSkipTestFiles = true
coverageThreshold = { line = 1.0 }
coveragePathIgnorePatterns = ["../**", "**/test.setup.ts", "**/test.dom.ts"]
